import type { NextPage } from "next";
import Head from "next/head";
import Banner from "../modules/banner/Banner";
import Explore from "../modules/explore/Explore";
import Footer from "../modules/footer/Footer";
import Header from "../modules/header/Header";
import LargeCard from "../modules/largeCard/LargeCard";
import LiveAnyWhere from "../modules/liveAnywhere/LiveAnyWhere";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
      <Explore />
      <LiveAnyWhere />
      <LargeCard />
      <Footer />
    </div>
  );
};

export default Home;
